version: '3'

services:
  atc-monitor:
    build: .
    volumes:
      - ./analysis_results:/app/analysis_results
      - ./monitoring_results:/app/monitoring_results
    environment:
      - TZ=UTC
    command: ["60"]  # Override default duration (seconds)